#!/bin/bash

set -e

BASE="${BASE:-ghcr.io/zifeitong/ubuntu-devpack}"
TAG="${1:-devpack}"

if [ "$(uname)" == "Darwin" ]; then
    container build . \
        --build-arg USER=$USER \
        --build-arg UID=$(id -u) \
        --build-arg BASE=$BASE \
        --build-arg GIT_AUTHOR_NAME="$(git config user.name)" \
        --build-arg GIT_AUTHOR_EMAIL="$(git config user.email)" \
        -t $TAG \
        -f Containerfile

    container run --rm \
        --name $TAG \
        -v $TAG-home:/home/$USER \
        $TAG \
        chown $USER:$USER /home/$USER
else
    podman build . \
        --build-arg USER=$USER \
        --build-arg UID=$(id -u) \
        --build-arg BASE=$BASE \
        --build-arg GIT_AUTHOR_NAME="$(git config user.name)" \
        --build-arg GIT_AUTHOR_EMAIL="$(git config user.email)" \
        -t $TAG \
        --pull=newer
fi
