#!/bin/bash

set -e

BASE="${BASE:-ghcr.io/zifeitong/ubuntu-devpack}"
TAG="${1:-devpack}"

if [ "$(uname)" == "Darwin" ]; then
    container build . --build-arg USER=$USER --build-arg UID=$(id -u) --build-arg BASE=$BASE -t $TAG -f Containerfile
    mkdir -p $HOME/devpack-home
else
    podman build . --build-arg USER=$USER --build-arg UID=$(id -u) --build-arg BASE=$BASE -t $TAG

    VOLUME_NAME=$TAG-home
    if ! podman volume inspect "$VOLUME_NAME" >/dev/null 2>&1; then
        podman volume create $VOLUME_NAME --label devpack
    fi
fi
