#!/bin/bash

set -e

IMAGE="${1:-devpack}"
COMMAND="${2:-fish}"

podman run --rm --interactive --tty --user=$USER --hostname $IMAGE -v $IMAGE-home:$HOME -v $(pwd):/src -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -w /src --rm --userns keep-id --privileged $IMAGE $COMMAND
