name: Create and push continer images

on:
  push:
    branches: ["latest"]

env:
  REGISTRY: ghcr.io
  USER_NAME: zifeitong
  IMAGE: ubuntu-devpack
  REPO: ghcr.io/zifeitong/ubuntu-devpack
  CUDA_IMAGE: cuda-devpack
  CUDA_REPO: ghcr.io/zifeitong/cuda-devpack

jobs:
  build-and-push-image:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Prepare env variables
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REPO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6.15.0
        with:
          platforms: ${{ matrix.platform }}
          context: .
          file: ${{ env.IMAGE }}.Containerfile
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,"name=${{ env.REPO }}",push-by-digest=true,name-canonical=true,push=true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2.2.2
        with:
          subject-name: ${{ env.REPO }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-multi-platform-images:
    runs-on: ubuntu-24.04

    needs:
      - build-and-push-image

    permissions:
      packages: write
      id-token: write

    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE }}
          package-type: "container"
          min-versions-to-keep: 16

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REPO }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REPO }}@sha256:%s ' *)

  build-and-push-cuda-image:
    needs:
      - merge-multi-platform-images

    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.CUDA_IMAGE }}
          package-type: "container"
          min-versions-to-keep: 16

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.CUDA_REPO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ${{ env.CUDA_IMAGE }}.Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2.2.2
        with:
          subject-name: ${{ env.CUDA_REPO }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
