name: Create and push a continer image

on:
  push:
    branches: ["latest"]

env:
  REGISTRY: ghcr.io
  USER_NAME: zifeitong

jobs:
  build-and-push-image:
    strategy:
      matrix:
        image: [ubuntu-devpack, cuda-devpack]
      fail-fast: true
      max-parallel: 1

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image }}
          package-type: "container"
          min-versions-to-keep: 16

      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.USER_NAME }}/${{ matrix.image }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ${{ matrix.image }}.Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.2.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.USER_NAME }}/${{ matrix.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
